# Generated by Django 4.2.3 on 2024-02-15 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=430)),
                ('salt', models.BinaryField(max_length=16)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
